### ISSUE TITLE
Spam E-mail via SMTP

### ISSUE THREAD

**Issue by ritik-malik** [Py-Contributors/awesomeScripts#259] opened 2020-10-09 14:21 UTC
## Spam E-mail via SMTP

**what will change** - Add a new script that sends X number of trash emails via your google account through terminal.
The client uses GSMTP which makes secure openssl connection & credentials in base64

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Bash

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ritik-malik** [comment] 2020-10-09 14:22
Hi, can I work on this?

**Comment by codeperfectplus** [comment] 2020-10-09 14:29
Duplicate of #133

**Closed as completed** 2020-10-09 16:36 UTC
Labels: good first issue
